name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-onlydev.txt
    - name: Run unittest
      run: |
        python -m unittest
    - name: Coverage test
      run: |
        coverage run --source . --parallel-mode -m unittest
        coverage combine
        coverage xml -i
    - name: Upload report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
